-- INSERT INTO AuthRole (authRoleId, roleType) VALUES (0,'ADMIN');
-- INSERT INTO AuthRole (authRoleId, roleType) VALUES (111,'USER');
--
-- INSERT INTO AuthUser (authUserId, username, password) VALUES (0,'test', 'password');
-- INSERT INTO AuthUser (authUserId, username, password) VALUES (111, 'johndoe', 'secret');
--
-- INSERT INTO user_roles (role_id, user_id) VALUES (0, 0); -- Assign ADMIN to 'test'
-- INSERT INTO user_roles (role_id, user_id) VALUES (111, 0); -- Assign USER to 'test'
-- INSERT INTO user_roles (role_id, user_id) VALUES (111, 111); -- Assign USER to 'johndoe';
